### ISSUE TITLE
Add examples from css-counter-styles

### ISSUE THREAD

**Issue by Crissov** [w3c/predefined-counter-styles#10]
The specification for [CSS Counter Styles Level 3](http://www.w3.org/TR/css-counter-styles-3/) contains several more or less useful examples for counters (or symbolic markers). Should they be repeated here?

I quote them below, slightly altered, for easy reference.

``` css
@counter-style triangle {
  system: cyclic;
  symbols: '‣';
  suffix: " ";
}

@counter-style box-corner {
  system: fixed;
  symbols: '◰' '◳' '◲' '◱';
  suffix: ': ';
}

@counter-style footnote {
  system: symbolic;
  symbols: '*' '⁑' '†' '‡'; /* anonymous variant also includes '§' */
  suffix: " ";
}

@counter-style upper-alpha-legal {
  system: symbolic;
  symbols: A B C D E F G H I J K L M N O P Q R S T U V W X Y Z;
}

@counter-style go {
  system: alphabetic;
  symbols: '⚪️' '⚫️'; /* original uses SVG images */
  suffix: " ";
}

@counter-style trinary {
  system: numeric;
  symbols: '0' '1' '2';
}

@counter-style dice {
  system: additive;
  additive-symbols: 6 '⚅', 5 '⚄', 4 '⚃', 3 '⚂', 2 '⚁', 1 '⚀';
  suffix: " ";
}

@counter-style decimal-paren {
  system: extends decimal;
  suffix: ") ";
}

@counter-style circled-lower-latin {
  system: alphabetic;
  speak-as: lower-latin;
  symbols: 'ⓐ' 'ⓑ' 'ⓒ' 'ⓓ' 'ⓔ' 'ⓕ' 'ⓖ' 'ⓗ' 'ⓘ' 'ⓙ' 'ⓚ' 'ⓛ' 'ⓜ' 
           'ⓝ' 'ⓞ' 'ⓟ' 'ⓠ' 'ⓡ' 'ⓢ' 'ⓣ' 'ⓤ' 'ⓥ' 'ⓦ' 'ⓧ' 'ⓨ' 'ⓩ';
  suffix: " ";
}
```

The last one is actually already included. It could alternatively be written as:

``` css
@counter-style lower-latin-in-circle {
  system: extends lower-latin;
  suffix: "\20DD "; /* Combining Enclosing Circle */
}

@counter-style lower-latin-in-square {
  system: extends lower-latin;
  suffix: "\20DE "; /* Combining Enclosing Square */
}
@counter-style lower-latin-in-diamond {
  system: extends lower-latin;
  suffix: "\20DF "; /* Combining Enclosing Diamond */
}
@counter-style lower-latin-in-triangle {
  system: extends lower-latin;
  suffix: "\20E4 "; /* Combining Enclosing Upward Pointing Triangle */
}
@counter-style lower-latin-forbidden {
  system: extends lower-latin;
  suffix: "\20E0 "; /* Combining Enclosing Circle Backslash */
}
@counter-style lower-latin-on-screen {
  system: extends lower-latin;
  suffix: "\20E2 "; /* Combining Enclosing Screen */
}
@counter-style lower-latin-on-key {
  system: extends lower-latin;
  suffix: "\20E3 "; /* Combining Enclosing Keycap */
}
```
