### ISSUE TITLE
Old Chinese Counting Rods

### ISSUE THREAD

**Issue by Crissov** [w3c/predefined-counter-styles#12]
``` css
/**
 * Unicode block “Ancient Chinese Digits” U+1D360–7F
 *
 * Ones: 𝍠 𝍡 𝍢 𝍣 𝍤  𝍥 𝍦 𝍧 𝍨 
 * Tens: 𝍩 𝍪 𝍫 𝍬 𝍭  𝍮 𝍯 𝍰 𝍱
 */
@counter-style counting-rods {
  system: additive;
  range: 1 99;
  additive-symbols: 90 '\1D371', 80 '\1D370', 70 '\1D36F', 60 '\1D36E', 
                    50 '\1D36D', 40 '\1D36C', 30 '\1D36B', 20 '\1D36A', 10 '\1D369', 
                     9 '\1D368',  8 '\1D367',  7 '\1D366',  6 '\1D365', 
                     5 '\1D364',  4 '\1D363',  3 '\1D362',  2 '\1D361',  1 '\1D360', 
}
```
